const hotels = [
  {
    ลำดับ: 1,
    name: "เทพธารินทร์",
    address: "3850 ถ.พระราม 4 แขวงพระโขนง",
    district: "คลองเตย",
    province: "กรุงเทพมหานคร",
    postalcode: 10110,
    tel: "02-3487000",
    region: "กรุงเทพมหานคร (Bangkok)",
  },
  {
    ลำดับ: 2,
    name: "กล้วยน้ำไท 1",
    address: "80 ซ.โรงพยาบาล 2 ถ.พระราม 4 แขวงคลองตัน",
    district: "คลองเตย",
    province: "กรุงเทพมหานคร",
    postalcode: 10110,
    tel: "02-7692000",
    region: "กรุงเทพมหานคร (Bangkok)",
  },
  {
    ลำดับ: 3,
    name: "สินแพทย์",
    address: "9/99 ถ.รามอินทรา กม 8.5 แขวงคันนายาว",
    district: "คันนายาว",
    province: "กรุงเทพมหานคร",
    postalcode: 10230,
    tel: "02-9485380-90",
    region: "กรุงเทพมหานคร (Bangkok)",
  },
  {
    ลำดับ: 4,
    name: "เซ็นทรัลเยนเนอรัล",
    address: "290 ถนนพหลโยธิน แขวงอนุสาวรีย์",
    district: "บางเขน",
    province: "กรุงเทพมหานคร",
    postalcode: 10220,
    tel: "02-5528777,02-5528801",
    region: "กรุงเทพมหานคร (Bangkok)",
  },
  {
    ลำดับ: 5,
    name: "เจ้าพระยา",
    address: "113/44 ถ.พระบรมราชชนนี บางบำหรุ",
    district: "บางพลัด",
    province: "กรุงเทพมหานคร",
    postalcode: 10700,
    tel: "02-4340117",
    region: "กรุงเทพมหานคร (Bangkok)",
  },
  {
    ลำดับ: 6,
    name: "เปาโล เกษตร (เมโย)",
    address: "2012/5-7 ถ.พหลโยธิน แขวงลาดยาว",
    district: "จตุจักร",
    province: "กรุงเทพมหานคร",
    postalcode: 10900,
    tel: "02-5791770-4",
    region: "กรุงเทพมหานคร (Bangkok)",
  },
  {
    ลำดับ: 7,
    name: "วิภาวดี",
    address: "51/3 ถ.งามวงศ์วาน แขวงลาดยาว",
    district: "จตุจักร",
    province: "กรุงเทพมหานคร",
    postalcode: 10900,
    tel: "02-9412800",
    region: "กรุงเทพมหานคร (Bangkok)",
  },
  {
    ลำดับ: 8,
    name: "บางปะกอก 9 อินเตอร์เนชั่นแนล",
    address: "362 ถ.พระราม 2 แขวงบางมด",
    district: "จอมทอง",
    province: "กรุงเทพมหานคร",
    postalcode: 10150,
    tel: "02-8771111",
    region: "กรุงเทพมหานคร (Bangkok)",
  },
  {
    ลำดับ: 9,
    name: "บางมด",
    address: "747 ถ.พระราม 2 แขวงบางมด",
    district: "จอมทอง",
    province: "กรุงเทพมหานคร",
    postalcode: 10150,
    tel: "02-8670606",
    region: "กรุงเทพมหานคร (Bangkok)",
  },
  {
    ลำดับ: 10,
    name: "มิชชั่น",
    address: "430 ถ.พิษณุโลก แขวงบางซื่อ",
    district: "ดุสิต",
    province: "กรุงเทพมหานคร",
    postalcode: 10300,
    tel: "02-2821100",
    region: "กรุงเทพมหานคร (Bangkok)",
  },
  {
    ลำดับ: 11,
    name: "ธนบุรี 2",
    address: "43/4 ถนนบรมราชชนนี แขวงศาลาธรรมสพน์",
    district: "ทวีวัฒนา",
    province: "กรุงเทพมหานคร",
    postalcode: 10170,
    tel: "02-4872100 (สายด่วน 1645)",
    region: "กรุงเทพมหานคร (Bangkok)",
  },
  {
    ลำดับ: 12,
    name: "สมิติเวช ธนบุรี",
    address: "337 ถนนสมเด็จพระเจ้าตากสิน แขวงสำเหร่",
    district: "ธนบุรี",
    province: "กรุงเทพมหานคร",
    postalcode: 10600,
    tel: "02-4380040",
    region: "กรุงเทพมหานคร (Bangkok)",
  },
  {
    ลำดับ: 13,
    name: "เกษมราษฎร์ บางแค",
    address: "586, 588 ถ.เพชรเกษม แขวงบางแคเหนือ",
    district: "บางแค",
    province: "กรุงเทพมหานคร",
    postalcode: 10160,
    tel: "02- 8048959",
    region: "กรุงเทพมหานคร (Bangkok)",
  },
  {
    ลำดับ: 14,
    name: "ธนบุรี 1",
    address: "34/1 ถ.อิสรภาพ ซอย 44",
    district: "บางกอกน้อย",
    province: "กรุงเทพมหานคร",
    postalcode: 10700,
    tel: "02-4120020",
    region: "กรุงเทพมหานคร (Bangkok)",
  },
  {
    ลำดับ: 15,
    name: "โรงพยาบาลทั่วไปขนาดกลาง วิชัยเวช แยกไฟฉาย (ศรีวิชัย 1)",
    address: "240/1-7 ถนนจรัญสนิทวงศ์ แขวงบ้านช่างหล่อ",
    district: "บางกอกน้อย",
    province: "กรุงเทพมหานคร",
    postalcode: 10700,
    tel: "02-4120055",
    region: "กรุงเทพมหานคร (Bangkok)",
  },
  {
    ลำดับ: 16,
    name: "เวชธานี",
    address: "1 ถ.ลาดพร้าว 111 แขวงคลองจั่น",
    district: "บางกะปิ",
    province: "กรุงเทพมหานคร",
    postalcode: 10240,
    tel: "02-7340000",
    region: "กรุงเทพมหานคร (Bangkok)",
  },
  {
    ลำดับ: 17,
    name: "รามคำแหง",
    address: "436 ถ.รามคำแหง แขวงหัวหมาก",
    district: "บางกะปิ",
    province: "กรุงเทพมหานคร",
    postalcode: 10240,
    tel: "02-3740200",
    region: "กรุงเทพมหานคร (Bangkok)",
  },
  {
    ลำดับ: 18,
    name: "นครธน",
    address: "1 ซอยพระรามที่ 2 ซอย 56 แขวงแสมดำ",
    district: "บางขุนเทียน",
    province: "กรุงเทพมหานคร",
    postalcode: 10150,
    tel: "02-4165454",
    region: "กรุงเทพมหานคร (Bangkok)",
  },
  {
    ลำดับ: 19,
    name: "พระราม 2",
    address: "78/1 หมู่ที่ ม.6 ซอย ถนน พระราม 2 ตำบล แสมดำ",
    district: "บางขุนเทียน",
    province: "กรุงเทพมหานคร",
    postalcode: 10150,
    tel: "02-4514920-30",
    region: "กรุงเทพมหานคร (Bangkok)",
  },
  {
    ลำดับ: 20,
    name: "เกษมราษฎร์ ประชาชื่น",
    address: "950 ถ.ประชาชื่น แขวงวงศ์สว่าง",
    district: "บางซื่อ",
    province: "กรุงเทพมหานคร",
    postalcode: 10800,
    tel: "02-9101600",
    region: "กรุงเทพมหานคร (Bangkok)",
  },
  {
    ลำดับ: 21,
    name: "บางโพ",
    address: "95 ถ.ประชาราษฎร์ สาย 2",
    district: "บางซื่อ",
    province: "กรุงเทพมหานคร",
    postalcode: 10800,
    tel: "02-5870136-55",
    region: "กรุงเทพมหานคร (Bangkok)",
  },
  {
    ลำดับ: 22,
    name: "ไทยนครินทร์",
    address: "345 ถ.บางนา-ตราด กม.3.5 แขวงบางนา",
    district: "บางนา",
    province: "กรุงเทพมหานคร",
    postalcode: 10260,
    tel: "02-3612727",
    region: "กรุงเทพมหานคร (Bangkok)",
  },
  {
    ลำดับ: 23,
    name: "กล้วยน้ำไท 2",
    address: "24 สุขุมวิท68 ( ซอย โสภณ )",
    district: "บางนา",
    province: "กรุงเทพมหานคร",
    postalcode: 10260,
    tel: "02-3994259-63",
    region: "กรุงเทพมหานคร (Bangkok)",
  },
  {
    ลำดับ: 24,
    name: "บางนา 1",
    address: "1302 ถนนบางนา - ตราด แขวงบางนา",
    district: "บางนา",
    province: "กรุงเทพมหานคร",
    postalcode: 10260,
    tel: "02-7468630-9",
    region: "กรุงเทพมหานคร (Bangkok)",
  },
  {
    ลำดับ: 25,
    name: "บางปะกอก 8",
    address: "1055 ถนนเอกชัย แขวงบางบอน",
    district: "บางบอน",
    province: "กรุงเทพมหานคร",
    postalcode: 10150,
    tel: "02-8944111",
    region: "กรุงเทพมหานคร (Bangkok)",
  },
  {
    ลำดับ: 26,
    name: "ยันฮี",
    address: "454 ถนนจรัญสนิทวงศ์ แขวงบางอ้อ",
    district: "บางพลัด",
    province: "กรุงเทพมหานคร",
    postalcode: 10700,
    tel: "02-8790300",
    region: "กรุงเทพมหานคร (Bangkok)",
  },
  {
    ลำดับ: 27,
    name: "ปิยะมินทร์",
    address: "35/2 ถ.บางนา-ตราด (กม.6)",
    district: "บางพลี",
    province: "สมุทรปราการ",
    postalcode: 10540,
    tel: "02-3160026,02-3160034",
    region: "กรุงเทพมหานคร (Bangkok)",
  },
  {
    ลำดับ: 28,
    name: "บีเอ็นเอช",
    address: "9/1 ถ.คอนแวนต์ สีลม",
    district: "บางรัก",
    province: "กรุงเทพมหานคร",
    postalcode: 10500,
    tel: "02-6862700",
    region: "กรุงเทพมหานคร (Bangkok)",
  },
  {
    ลำดับ: 29,
    name: "มเหสักข์",
    address: "46/7-9 ถ.มเหสักข์ แขวงสีลม",
    district: "บางรัก",
    province: "กรุงเทพมหานคร",
    postalcode: 10500,
    tel: "02-6357123",
    region: "กรุงเทพมหานคร (Bangkok)",
  },
  {
    ลำดับ: 30,
    name: "พญาไท นวมินทร์ (เปาโล เมโมเรียล นวมินทร์)",
    address: "44/505 ถ.นวมินทร์ แขวงคลองกุ่ม",
    district: "บึงกุ่ม",
    province: "กรุงเทพมหานคร",
    postalcode: 10230,
    tel: "02-9447111",
    region: "กรุงเทพมหานคร (Bangkok)",
  },
  {
    ลำดับ: 31,
    name: "หัวเฉียว",
    address: "665 ถ.บำรุงเมือง",
    district: "ป้อมปราบศัตรูพ่าย",
    province: "กรุงเทพมหานคร",
    postalcode: 10100,
    tel: "02-2231351",
    region: "กรุงเทพมหานคร (Bangkok)",
  },
  {
    ลำดับ: 32,
    name: "เปาโล เมโมเรียล",
    address: "670/1 สี่แยกสะพานควาย แขวงสามเสนใน",
    district: "พญาไท",
    province: "กรุงเทพมหานคร",
    postalcode: 10400,
    tel: "02-2797000-9",
    region: "กรุงเทพมหานคร (Bangkok)",
  },
  {
    ลำดับ: 33,
    name: "พญาไท 2",
    address: "943 ถ.พหลโยธิน สามเสนใน",
    district: "พญาไท",
    province: "กรุงเทพมหานคร",
    postalcode: 10400,
    tel: "02-6172444",
    region: "กรุงเทพมหานคร (Bangkok)",
  },
  {
    ลำดับ: 34,
    name: "วิชัยยุทธ",
    address: "114/4 ถ.เศรษฐศิริ แขวงสามเสนใน",
    district: "พญาไท",
    province: "กรุงเทพมหานคร",
    postalcode: 10400,
    tel: "02-2657777",
    region: "กรุงเทพมหานคร (Bangkok)",
  },
  {
    ลำดับ: 35,
    name: "ศิครินทร์",
    address: "4/29 ม.10 ถ.ศรีนครินทร์ แขวงบางนา",
    district: "พระโขนง",
    province: "กรุงเทพมหานคร",
    postalcode: 10260,
    tel: "02-3669900-99",
    region: "กรุงเทพมหานคร (Bangkok)",
  },
  {
    ลำดับ: 36,
    name: "พญาไท 3",
    address: "111 ถนนเพชรเกษม แขวงปากคลองภาษีเจริญ",
    district: "ภาษีเจริญ",
    province: "กรุงเทพมหานคร",
    postalcode: 10160,
    tel: "02-467 1111",
    region: "กรุงเทพมหานคร (Bangkok)",
  },
  {
    ลำดับ: 37,
    name: "เพชรเกษม 2",
    address: "675 ถนนเพชรเกษม แขวงบางหว้า",
    district: "ภาษีเจริญ",
    province: "กรุงเทพมหานคร",
    postalcode: 10160,
    tel: "02-4555599",
    region: "กรุงเทพมหานคร (Bangkok)",
  },
  {
    ลำดับ: 38,
    name: "เสรีรักษ์",
    address: "44 ถ.เสรีไทย แขวงมีนบุรี",
    district: "มีนบุรี",
    province: "กรุงเทพมหานคร",
    postalcode: 10510,
    tel: "02-9189888",
    region: "กรุงเทพมหานคร (Bangkok)",
  },
  {
    ลำดับ: 39,
    name: "นวมินทร์ 1",
    address: "41 ซอยสีหบุรานุกิจ 10 ถนนสีหบุรานุกิจ แขวงมีนบุรี",
    district: "มีนบุรี",
    province: "กรุงเทพมหานคร",
    postalcode: 10510,
    tel: "02-9185080",
    region: "กรุงเทพมหานคร (Bangkok)",
  },
  {
    ลำดับ: 40,
    name: "นวมินทร์ 9",
    address: "96 หมู่ 13 ถนนสีหบุรานุกิจ แขวงมีนบุรี",
    district: "มีนบุรี",
    province: "กรุงเทพมหานคร",
    postalcode: 10510,
    tel: "02-5181818",
    region: "กรุงเทพมหานคร (Bangkok)",
  },
  {
    ลำดับ: 41,
    name: "พญาไท 1",
    address: "364/1 ถ.ศรีอยุธยา",
    district: "ราชเทวี",
    province: "กรุงเทพมหานคร",
    postalcode: 10400,
    tel: "02-6401111",
    region: "กรุงเทพมหานคร (Bangkok)",
  },
  {
    ลำดับ: 42,
    name: "บางปะกอก 1",
    address: "2 ซอยสุขสวัสดิ์ 25/1 ถนนสุขสวัสดิ์ แขวงบางปะกอก",
    district: "ราษฎร์บูรณะ",
    province: "กรุงเทพมหานคร",
    postalcode: 10140,
    tel: "02-8721111-91",
    region: "กรุงเทพมหานคร (Bangkok)",
  },
  {
    ลำดับ: 43,
    name: "ราษฎร์บูรณะ",
    address: "377 ถนนราษฎร์พัฒนา แขวงบางปะกอก",
    district: "ราษฎร์บูรณะ",
    province: "กรุงเทพมหานคร",
    postalcode: 10140,
    tel: "02-4270175-9",
    region: "กรุงเทพมหานคร (Bangkok)",
  },
  {
    ลำดับ: 44,
    name: "สุขสวัสดิ์",
    address: "272 ถนนสุขสวัสดิ์ แขางบางปะกอก",
    district: "ราษฏร์บูรณะ",
    province: "กรุงเทพมหานคร",
    postalcode: 10140,
    tel: "0-2874-6766-70",
    region: "กรุงเทพมหานคร (Bangkok)",
  },
  {
    ลำดับ: 45,
    name: "เปาโล เมโมเรียล โชคชัย 4",
    address: "1 ถนนโชคชัย 4 แขวงลาดพร้าว",
    district: "ลาดพร้าว",
    province: "กรุงเทพมหานคร",
    postalcode: 10230,
    tel: "02-5142157-9",
    region: "กรุงเทพมหานคร (Bangkok)",
  },
  {
    ลำดับ: 46,
    name: "ลาดพร้าว",
    address: "2699 ถ.ลาดพร้าว แขวงคลองเจ้าคุณสิงห์",
    district: "วังทองหลาง",
    province: "กรุงเทพมหานคร",
    postalcode: 10310,
    tel: "02-9322929",
    region: "กรุงเทพมหานคร (Bangkok)",
  },
  {
    ลำดับ: 47,
    name: "คามิลเลียน",
    address: "423 ซอยทองหล่อ ถนนสุขุมวิท 55 แขวงคลองตันเหนือ",
    district: "วัฒนา",
    province: "กรุงเทพมหานคร",
    postalcode: 10110,
    tel: "02-1851444",
    region: "กรุงเทพมหานคร (Bangkok)",
  },
  {
    ลำดับ: 48,
    name: "บ้านแพ้วสาขาพร้อมมิตร",
    address: "12 ซ.พร้อมมิตร (สุขุมวิท 39)",
    district: "วัฒนา",
    province: "กรุงเทพมหานคร",
    postalcode: 10110,
    tel: "02-2590376",
    region: "กรุงเทพมหานคร (Bangkok)",
  },
  {
    ลำดับ: 49,
    name: "บำรุงราษฎร์",
    address: "33 สุขุมวิท ซอย 3 (นานาเหนือ) ถ.สุขุมวิท แขวงคลองตันเหนือ",
    district: "วัฒนา",
    province: "กรุงเทพมหานคร",
    postalcode: 10110,
    tel: "02-6671000",
    region: "กรุงเทพมหานคร (Bangkok)",
  },
  {
    ลำดับ: 50,
    name: "สมิติเวช สุขุมวิท",
    address: "133 ซ.สุขุมวิท 49 ถ.สุขุมวิท แขวงคลองตันเหนือ",
    district: "วัฒนา",
    province: "กรุงเทพมหานคร",
    postalcode: 10110,
    tel: "02-3920011",
    region: "กรุงเทพมหานคร (Bangkok)",
  },
  {
    ลำดับ: 51,
    name: "สุขุมวิท",
    address: "1411 ถ.สุขุมวิท แขวงพระโขนงเหนือ",
    district: "วัฒนา",
    province: "กรุงเทพมหานคร",
    postalcode: 10110,
    tel: "02-3910011",
    region: "กรุงเทพมหานคร (Bangkok)",
  },
  {
    ลำดับ: 52,
    name: "กรุงเทพคริสเตียน",
    address: "124ถ.สีลม",
    district: "บางรัก",
    province: "กรุงเทพมหานคร",
    postalcode: 10500,
    tel: "02-2351000-7",
    region: "กรุงเทพมหานคร (Bangkok)",
  },
  {
    ลำดับ: 53,
    name: "แพทย์ปัญญา",
    address: "124-126 ถ.รามคำแหง",
    district: "สวนหลวง",
    province: "กรุงเทพมหานคร",
    postalcode: 10250,
    tel: "02-3140726-9",
    region: "กรุงเทพมหานคร (Bangkok)",
  },
  {
    ลำดับ: 54,
    name: "วิภาราม",
    address: "2677 ถ.พัฒนาการ แขวงสวนหลวง",
    district: "สวนหลวง",
    province: "กรุงเทพมหานคร",
    postalcode: 10250,
    tel: "02-7222500",
    region: "กรุงเทพมหานคร (Bangkok)",
  },
  {
    ลำดับ: 55,
    name: "สมิติเวช ศรีนครินทร์",
    address: "488 ถ.ศรีนครินทร์ แขวงสวนหลวง",
    district: "สวนหลวง",
    province: "กรุงเทพมหานคร",
    postalcode: 10250,
    tel: "02-7317000",
    region: "กรุงเทพมหานคร (Bangkok)",
  },
  {
    ลำดับ: 56,
    name: "การุญเวช สุขาภิบาล 3",
    address: "88,90,92, ถ. รามคำแหง แขวงสะพานสูง",
    district: "สะพานสูง",
    province: "กรุงเทพมหานคร",
    postalcode: 10240,
    tel: "02-7293000",
    region: "กรุงเทพมหานคร (Bangkok)",
  },
  {
    ลำดับ: 57,
    name: "เซนต์หลุยส์",
    address: "27 ถ.สาธรใต้",
    district: "สาทร",
    province: "กรุงเทพมหานคร",
    postalcode: 10120,
    tel: "02-6755000",
    region: "กรุงเทพมหานคร (Bangkok)",
  },
  {
    ลำดับ: 58,
    name: "บี.แคร์ เมดิคอลเซ็นเตอร์",
    address: "29 ม.6 แขวงสายไหม",
    district: "สายไหม",
    province: "กรุงเทพมหานคร",
    postalcode: 10220,
    tel: "02-5233359-71",
    region: "กรุงเทพมหานคร (Bangkok)",
  },
  {
    ลำดับ: 59,
    name: "สายไหม",
    address: "91 หมู่ 1 ถนนเฉลิมพงษ์ แขวงสายไหม",
    district: "สายไหม",
    province: "กรุงเทพมหานคร",
    postalcode: 10220,
    tel: "02-9918999",
    region: "กรุงเทพมหานคร (Bangkok)",
  },
  {
    ลำดับ: 60,
    name: "วิชัยเวช อินเตอร์เนชั่นแนล หนองแขม",
    address: "456-456/9 ถ.เพชรเกษม แขวงหนองค้างพลู",
    district: "หนองแขม",
    province: "กรุงเทพมหานคร",
    postalcode: 10160,
    tel: "02-8074044 , 02-4416999",
    region: "กรุงเทพมหานคร (Bangkok)",
  },
  {
    ลำดับ: 61,
    name: "มงกุฎวัฒนะ",
    address: "34/40 ถ.แจ้งวัฒนะ แขวงทุ่งสองห้อง",
    district: "หลักสี่",
    province: "กรุงเทพมหานคร",
    postalcode: 10210,
    tel: "02-5745000",
    region: "กรุงเทพมหานคร (Bangkok)",
  },
  {
    ลำดับ: 62,
    name: "กรุงเทพ",
    address: "2 ซ.ศูนย์วิจัย 7 ถ.เพชรบุรีตัดใหม่",
    district: "ห้วยขวาง",
    province: "กรุงเทพมหานคร",
    postalcode: 10310,
    tel: "02-3103000",
    region: "กรุงเทพมหานคร (Bangkok)",
  },
  {
    ลำดับ: 63,
    name: "ปิยะเวท",
    address: "998 ถ.ริมคลองสามเสนใน บางกะปิ",
    district: "ห้วยขวาง",
    province: "กรุงเทพมหานคร",
    postalcode: 10320,
    tel: "02-6256500",
    region: "กรุงเทพมหานคร (Bangkok)",
  },
  {
    ลำดับ: 64,
    name: "พระรามเก้า",
    address: "99 ถ.พระราม 9 แขวงบางกะปิ",
    district: "ห้วยขวาง",
    province: "กรุงเทพมหานคร",
    postalcode: 10320,
    tel: "02-2488020",
    region: "กรุงเทพมหานคร (Bangkok)",
  },
  {
    ลำดับ: 65,
    name: "เพชรเวช",
    address: "2469/13 , 15 แขวงบางกะปิ ถนนเพชรบุรีตัดใหม่",
    district: "ห้วยขวาง",
    province: "กรุงเทพมหานคร",
    postalcode: 10320,
    tel: "02-7181515",
    region: "กรุงเทพมหานคร (Bangkok)",
  },
  {
    ลำดับ: 66,
    name: "กรุงเทพ ไชน่าทาวน์",
    address: "624 ถ.เยาวราช",
    district: "สัมพันธวงศ์",
    province: "กรุงเทพมหานคร",
    postalcode: 10100,
    tel: "02-1187888",
    region: "กรุงเทพมหานคร (Bangkok)",
  },
  {
    ลำดับ: 1,
    name: "นนทเวช",
    address: "432 ถนนงามวงศ์วาน ตำบลบางเขน",
    district: "เมือง",
    province: "นนทบุรี",
    postalcode: 11000,
    tel: "02-5890102-7",
    region: "ปริมณฑล ( Perimeter )",
  },
  {
    ลำดับ: 2,
    name: "เกษมราษฎร์ อินเตอร์เนชั่นแนล รัตนาธิเบศร์",
    address: "60 ม.6 ถ.ตลิ่งชัน-สุพรรณบุรี ต.เสาธงหิน",
    district: "บางใหญ่",
    province: "นนทบุรี",
    postalcode: 11140,
    tel: "02-5940020-65",
    region: "ปริมณฑล ( Perimeter )",
  },
  {
    ลำดับ: 3,
    name: "กรุงไทย",
    address: "56/96 ม.5 ต.ปากเกร็ด",
    district: "ปากเกร็ด",
    province: "นนทบุรี",
    postalcode: 11120,
    tel: "02-5822299",
    region: "ปริมณฑล ( Perimeter )",
  },
  {
    ลำดับ: 4,
    name: "เวิลด์เมดิคอลเซ็นเตอร์",
    address: "44 หมู่ 4 ถนนแจ้งวัฒนะ ตำบลปากเกร็ด",
    district: "ปากเกร็ด",
    province: "นนทบุรี",
    postalcode: 11120,
    tel: "02 - 836999",
    region: "ปริมณฑล ( Perimeter )",
  },
  {
    ลำดับ: 5,
    name: "เกษมราษฎร์ รัตนาธิเบศร์ (การุญเวช รัตนาธิเบศร์)",
    address: "58 หมู่ 1 ต.บางรักพัฒนา",
    district: "บางบัวทอง",
    province: "นนทบุรี",
    postalcode: 11110,
    tel: "02-9213400-9",
    region: "ปริมณฑล ( Perimeter )",
  },
  {
    ลำดับ: 6,
    name: "กรุงสยามเซนต์คาร์ลอส",
    address: "5/84 ม.2 ถ.ติวานนท์ ต.บ้านกลาง",
    district: "เมือง",
    province: "ปทุมธานี",
    postalcode: 12000,
    tel: "02-9756700",
    region: "ปริมณฑล ( Perimeter )",
  },
  {
    ลำดับ: 7,
    name: "การุญเวช ปทุมธานี",
    address: "98 หมู่ 13 ถ.พหลโยธิน กม.46 ต.คลองหนึ่ง",
    district: "คลองหลวง",
    province: "ปทุมธานี",
    postalcode: 12120,
    tel: "02-5294533",
    region: "ปริมณฑล ( Perimeter )",
  },
  {
    ลำดับ: 8,
    name: "ภัทร ธนบุรี",
    address: "32/410 หมู่ 6 ถ.พหลโยธิน ต.คลองหนึ่ง",
    district: "คลองหลวง",
    province: "ปทุมธานี",
    postalcode: 12120,
    tel: "02-9018081-2",
    region: "ปริมณฑล ( Perimeter )",
  },
  {
    ลำดับ: 9,
    name: "บางปะกอก-รังสิต 2(เอกปทุม)",
    address: "757 ถ.รังสิต-นครนายก ต.ประชาธิปัตย์",
    district: "ธัญบุรี",
    province: "ปทุมธานี",
    postalcode: 12130,
    tel: "02-9962211-15",
    region: "ปริมณฑล ( Perimeter )",
  },
  {
    ลำดับ: 10,
    name: "ปทุมเวช",
    address: "1 ซ.รังสิต-ปทุมธานี 6",
    district: "ธัญบุรี",
    province: "ปทุมธานี",
    postalcode: 12130,
    tel: "02-5671991-9",
    region: "ปริมณฑล ( Perimeter )",
  },
  {
    ลำดับ: 11,
    name: "แพทย์รังสิต",
    address: "733/345 ม.8 ถ.พหลโยธิน ต.คูคต",
    district: "ลำลูกกา",
    province: "ปทุมธานี",
    postalcode: 12130,
    tel: "02-9989999",
    region: "ปริมณฑล ( Perimeter )",
  },
  {
    ลำดับ: 12,
    name: "เฉพาะทางแม่และเด็กแพทย์รังสิต",
    address: "733/347 หมู่ 8 ถนนพหลโยธิน ตำบลคูคต",
    district: "ลำลูกกา",
    province: "ปทุมธานี",
    postalcode: 12130,
    tel: "02-9989888",
    region: "ปริมณฑล ( Perimeter )",
  },
  {
    ลำดับ: 13,
    name: "เปาโล รังสิต",
    address: "11/1 ถ.รังสิต-นครนายก ต.ประชาธิปัตย์",
    district: "ธัญบุรี",
    province: "ปทุมธานี",
    postalcode: 12130,
    tel: "02-532-4777-8",
    region: "ปริมณฑล ( Perimeter )",
  },
  {
    ลำดับ: 14,
    name: "เปาโล เมโมเรียล สมุทรปราการ",
    address: "123 ม.8 ถ.ศรีนครินทร์ ต.บางเมือง",
    district: "เมือง",
    province: "สมุทรปราการ",
    postalcode: 10270,
    tel: "02-3892555",
    region: "ปริมณฑล ( Perimeter )",
  },
  {
    ลำดับ: 15,
    name: "เมืองสมุทรปากน้ำ",
    address: "156 ถนนเทศบาล 12 ต.ปากน้ำ",
    district: "เมือง",
    province: "สมุทรปราการ",
    postalcode: 10270,
    tel: "02-1737766-75",
    region: "ปริมณฑล ( Perimeter )",
  },
  {
    ลำดับ: 16,
    name: "รัทรินทร์",
    address: "999/23-29 ถ.สุขุมวิท ต.บางปูใหม่",
    district: "เมือง",
    province: "สมุทรปราการ",
    postalcode: 10280,
    tel: "02-3232991-7",
    region: "ปริมณฑล ( Perimeter )",
  },
  {
    ลำดับ: 17,
    name: "สำโรงการแพทย์",
    address: "1748 ม.1 ต.สำโรงเหนือ",
    district: "เมือง",
    province: "สมุทรปราการ",
    postalcode: 10270,
    tel: "02-3610070-9",
    region: "ปริมณฑล ( Perimeter )",
  },
  {
    ลำดับ: 18,
    name: "บางนา2",
    address: "9/9 ม.3ถ.บางนา - ตราด กม.23 ต.บางเสาธง",
    district: "บางเสาธง",
    province: "สมุทรปราการ",
    postalcode: 10540,
    tel: "02-7401800-6",
    region: "ปริมณฑล ( Perimeter )",
  },
  {
    ลำดับ: 19,
    name: "จุฬารัตน์3",
    address: "88/8-9 หมู่ 11 ถนนเทพารักษ์ กม.145 ตำบลบางปลา",
    district: "บางพลี",
    province: "สมุทรปราการ",
    postalcode: 10540,
    tel: "02-7692900-99",
    region: "ปริมณฑล ( Perimeter )",
  },
  {
    ลำดับ: 20,
    name: "จุฬารัตน์9",
    address: "90/5 หมู่ที่ ม.13 ตำบลราชเทวะ",
    district: "บางพลี",
    province: "สมุทรปราการ",
    postalcode: 10540,
    tel: "02-7389900-9",
    region: "ปริมณฑล ( Perimeter )",
  },
  {
    ลำดับ: 21,
    name: "บางนา 5",
    address: "55 หมู่ 4 ต.บางพลีใหญ่",
    district: "บางพลี",
    province: "สมุทรปราการ",
    postalcode: 10540,
    tel: "02-1381155-65",
    region: "ปริมณฑล ( Perimeter )",
  },
  {
    ลำดับ: 22,
    name: "เมืองสมุทรปู่เจ้าฯ",
    address: "83/16 หมู่ 7 ถ.ปู่เจ้าสมิงพราย ต.สำโรงกลาง",
    district: "พระประแดง",
    province: "สมุทรปราการ",
    postalcode: 10310,
    tel: "02-7542800-9",
    region: "ปริมณฑล ( Perimeter )",
  },
  {
    ลำดับ: 23,
    name: "วิภาราม ชัยปราการ",
    address: "555 หมู่3 ถ.ปู่เจ้าสมิงพราย ต.สำโรงกลาง",
    district: "พระประแดง",
    province: "สมุทรปราการ",
    postalcode: 10250,
    tel: "02-3639222",
    region: "ปริมณฑล ( Perimeter )",
  },
  {
    ลำดับ: 24,
    name: "บางปะกอก 3",
    address: "27/14 หมู่ 10 ถ.สุขสวัสดิ์ ต.บางครุ",
    district: "พระประแดง",
    province: "สมุทรปราการ",
    postalcode: 10130,
    tel: "02-8187555",
    region: "ปริมณฑล ( Perimeter )",
  },
  {
    ลำดับ: 25,
    name: "กรุงเทพพระประแดง",
    address: "288 ถ.สุขสวัสดิ์ ม.1 ต.ปากคลองบางปลากด",
    district: "พระสมุทรเจดีย์",
    province: "สมุทรปราการ",
    postalcode: 10290,
    tel: "02-8157141-50",
    region: "ปริมณฑล ( Perimeter )",
  },
  {
    ลำดับ: 1,
    name: "กาญจนบุรี เมโมเรียล",
    address: "111 ถ.แสงชูโต ต.ท่ามะขาม",
    district: "เมือง",
    province: "กาญจนบุรี",
    postalcode: 71000,
    tel: "034-624191",
    region: "ภำคกลำง (CENTRAL)",
  },
  {
    ลำดับ: 2,
    name: "ธนกาญจน์",
    address: "20/20 ถ.แสงชูโต ต.บางใต้",
    district: "เมือง",
    province: "กาญจนบุรี",
    postalcode: 71000,
    tel: "034-622366-75",
    region: "ภำคกลำง (CENTRAL)",
  },
  {
    ลำดับ: 3,
    name: "ท่าม่วง",
    address: "978/1 ถนนแสงชูโต หมู่ 3 ต.ท่าม่วง",
    district: "ท่าม่วง",
    province: "กาญจนบุรี",
    postalcode: 71110,
    tel: "034-613166",
    region: "ภำคกลำง (CENTRAL)",
  },
  {
    ลำดับ: 4,
    name: "ท่าเรือ",
    address: "456 ถ. แสงชูโต ต.ท่าเรือ",
    district: "ท่ามะกา",
    province: "กาญจนบุรี",
    postalcode: 71120,
    tel: "034-636792-3",
    region: "ภำคกลำง (CENTRAL)",
  },
  {
    ลำดับ: 5,
    name: "รวมแพทย์ชัยนาท",
    address: "170 หมู่ 4 ต.บ้านกล้วย",
    district: "เมือง",
    province: "ชัยนาท",
    postalcode: 17000,
    tel: "056-413017-8",
    region: "ภำคกลำง (CENTRAL)",
  },
  {
    ลำดับ: 6,
    name: "เทพากร",
    address: "24 ซอย1 ถนนเทศา ตำบลพระปฐมเจดีย์",
    district: "เมือง",
    province: "นครปฐม",
    postalcode: 73000,
    tel: "034-212718-27",
    region: "ภำคกลำง (CENTRAL)",
  },
  {
    ลำดับ: 7,
    name: "กรุงเทพคริสเตียน นครปฐม",
    address: "173 ถ.25 มกรา ต.พระปฐมเจดีย์",
    district: "เมือง",
    province: "นครปฐม",
    postalcode: 73000,
    tel: "034-213453-60",
    region: "ภำคกลำง (CENTRAL)",
  },
  {
    ลำดับ: 8,
    name: "กรุงเทพสนามจันทร์ (สนามจันทร์)",
    address: "1194 ถ.เพชรเกษม ต.สนามจันทร์",
    district: "เมือง",
    province: "นครปฐม",
    postalcode: 73000,
    tel: "034-219600",
    region: "ภำคกลำง (CENTRAL)",
  },
  {
    ลำดับ: 9,
    name: "ศาลายา",
    address: "95 ม.3 ซอย ถนน ศาลายา-นครชัยศรี ตำบล ศาลายา",
    district: "พุทธมณฑล",
    province: "นครปฐม",
    postalcode: 73170,
    tel: "02-8892601-7",
    region: "ภำคกลำง (CENTRAL)",
  },
  {
    ลำดับ: 10,
    name: "ร่มฉัตร",
    address: "748/1 ถ.โกสีย์ ต. ปากน้ำโพ",
    district: "เมือง",
    province: "นครสวรรค์",
    postalcode: 60000,
    tel: "056-312481-90",
    region: "ภำคกลำง (CENTRAL)",
  },
  {
    ลำดับ: 11,
    name: "รวมแพทย์ นครสวรรค์",
    address: "276,276/2 ถ.สวรรค์วิถี ต.ปากน้ำโพ",
    district: "เมือง",
    province: "นครสวรรค์",
    postalcode: 60000,
    tel: "056-223600,056-223750",
    region: "ภำคกลำง (CENTRAL)",
  },
  {
    ลำดับ: 12,
    name: "ปากน้ำโพ 2 (รัตนเวช นครสวรรค์)",
    address: "62 ถ.อรรถกวี ต.ปากน้ำโพ",
    district: "เมือง",
    province: "นครสวรรค์",
    postalcode: 60000,
    tel: "056-212212-3",
    region: "ภำคกลำง (CENTRAL)",
  },
  {
    ลำดับ: 13,
    name: "ศรีสวรรค์",
    address: "ง.33/64 ถนนดาวดึงส์ ต.ปากน้ำโพ",
    district: "เมือง",
    province: "นครสวรรค์",
    postalcode: 60000,
    tel: "056-311626-35",
    region: "ภำคกลำง (CENTRAL)",
  },
  {
    ลำดับ: 14,
    name: "ปากน้ำโพ",
    address: "96/12 ถ.เอเชีย ต.นครสวรรค์",
    district: "เมือง",
    province: "นครสวรรค์",
    postalcode: 60000,
    tel: "056-225501-4",
    region: "ภำคกลำง (CENTRAL)",
  },
  {
    ลำดับ: 15,
    name: "มหาชัยเพชรรัชต์ (เพชรรัชต์ เพชรบุรี)",
    address: "99/9 ม.6 สี่แยกบันไดอิฐ ต.บ้านหม้อ",
    district: "เมือง",
    province: "เพชรบุรี",
    postalcode: 76000,
    tel: "032-417070-9",
    region: "ภำคกลำง (CENTRAL)",
  },
  {
    ลำดับ: 16,
    name: "เมืองเพชร (เมืองเพชร ธนบุรี)",
    address: "150 หมู่6 ถ.เพชรเกษม ต.ต้นมะม่วง",
    district: "เมือง",
    province: "เพชรบุรี",
    postalcode: 76000,
    tel: "032-415191-9",
    region: "ภำคกลำง (CENTRAL)",
  },
  {
    ลำดับ: 17,
    name: "ศุภมิตรเสนา",
    address: "34/4 หมู่5 ต.บางนมโค",
    district: "เสนา",
    province: "พระนครศรีอยุธยา",
    postalcode: 13110,
    tel: "035-289572-79",
    region: "ภำคกลำง (CENTRAL)",
  },
  {
    ลำดับ: 18,
    name: "การุญเวช อยุธยา",
    address: "61/9 หมู่ 4 ถ.พหลโยธิน กม.53 ต.คลองจิก",
    district: "บางปะอิน",
    province: "พระนครศรีอยุธยา",
    postalcode: 13160,
    tel: "035-315100-99",
    region: "ภำคกลำง (CENTRAL)",
  },
  {
    ลำดับ: 19,
    name: "ราชธานี",
    address: "111 หมู่ 3 ถ.โรจนะ ต.คลองสวนพลู",
    district: "พระนครศรีอยุธยา",
    province: "พระนครศรีอยุธยา",
    postalcode: 13000,
    tel: "035-335555",
    region: "ภำคกลำง (CENTRAL)",
  },
  {
    ลำดับ: 20,
    name: "ราชธานี โรจนะ",
    address: "78 หมู่3 ถนนโรจนะ ต.สามเรือน",
    district: "บางปะอิน",
    province: "พระนครศรีอยุธยา",
    postalcode: 13160,
    tel: "035-249249",
    region: "ภำคกลำง (CENTRAL)",
  },
  {
    ลำดับ: 21,
    name: "เมืองราช",
    address: "59/3 ถ.เพชรเกษมสายเก่า ต. หน้าเมือง",
    district: "เมือง",
    province: "ราชบุรี",
    postalcode: 70000,
    tel: "032-322274-80",
    region: "ภำคกลำง (CENTRAL)",
  },
  {
    ลำดับ: 22,
    name: "พร้อมแพทย์",
    address: "77/4 ถ.คฑาธร ต.หน้าเมือง",
    district: "เมือง",
    province: "ราชบุรี",
    postalcode: 70000,
    tel: "032-315234-9",
    region: "ภำคกลำง (CENTRAL)",
  },
  {
    ลำดับ: 23,
    name: "ดำเนินสะดวก",
    address: "146 หมู่ 4 ต.ท่านัด",
    district: "ดำเนินสะดวก",
    province: "ราชบุรี",
    postalcode: 70130,
    tel: "032-246000-15",
    region: "ภำคกลำง (CENTRAL)",
  },
  {
    ลำดับ: 24,
    name: "ซานคามิลโล",
    address: "31 ม.10 ต.สวนกล้วย",
    district: "บ้านโป่ง",
    province: "ราชบุรี",
    postalcode: 70110,
    tel: "032-211143",
    region: "ภำคกลำง (CENTRAL)",
  },
  {
    ลำดับ: 25,
    name: "เบญจรมย์",
    address: "116 หมู่8 ต.ป่าตาล",
    district: "เมือง",
    province: "ลพบุรี",
    postalcode: 15000,
    tel: "036-413933",
    region: "ภำคกลำง (CENTRAL)",
  },
  {
    ลำดับ: 26,
    name: "เมืองนารายณ์",
    address: "84 หมู่ 3 ต.ท่าศาลา",
    district: "เมือง",
    province: "ลพบุรี",
    postalcode: 15000,
    tel: "036-420666",
    region: "ภำคกลำง (CENTRAL)",
  },
  {
    ลำดับ: 27,
    name: "เอกชัย",
    address: "99/9 หมู่ 4 ต. โคกขาม",
    district: "เมือง",
    province: "สมุทรสาคร",
    postalcode: 74000,
    tel: "034-417999",
    region: "ภำคกลำง (CENTRAL)",
  },
  {
    ลำดับ: 28,
    name: "มหาชัย 1",
    address: "927/43 ค ถ.เศรษฐกิจ 1 ต.มหาชัย",
    district: "เมือง",
    province: "สมุทรสาคร",
    postalcode: 74000,
    tel: "034-424990",
    region: "ภำคกลำง (CENTRAL)",
  },
  {
    ลำดับ: 29,
    name: "มหาชัย 3",
    address: "927/45 ถ.เศรษฐกิจ 1 ต.มหาชัย",
    district: "เมือง",
    province: "สมุทรสาคร",
    postalcode: 74000,
    tel: "034-429111",
    region: "ภำคกลำง (CENTRAL)",
  },
  {
    ลำดับ: 30,
    name: "วิชัยเวช อินเตอร์เนชั่นแนล สมุทรสาคร",
    address: "93/256 ถนนเศรษฐกิจ1 ต.ท่าทราย",
    district: "เมือง",
    province: "สมุทรสาคร",
    postalcode: 74000,
    tel: "034-826709-10",
    region: "ภำคกลำง (CENTRAL)",
  },
  {
    ลำดับ: 31,
    name: "สมุทรสาคร",
    address: "1500 ถ.เอกชัย ต.มหาชัย",
    district: "เมือง",
    province: "สมุทรสาคร",
    postalcode: 74000,
    tel: "034-837521,034-427099",
    region: "ภำคกลำง (CENTRAL)",
  },
  {
    ลำดับ: 32,
    name: "วิภาราม สมุทรสาคร",
    address: "9/19 หมู่2 ต.บางกระเจ้า",
    district: "เมือง",
    province: "สมุทรสาคร",
    postalcode: 74000,
    tel: "034 - 116999",
    region: "ภำคกลำง (CENTRAL)",
  },
  {
    ลำดับ: 33,
    name: "มหาชัย 2",
    address: "301/1 ม.6 ต.อ้อมน้อย",
    district: "กระทุ่มเบน",
    province: "สมุทรสาคร",
    postalcode: 74130,
    tel: "02-4203200",
    region: "ภำคกลำง (CENTRAL)",
  },
  {
    ลำดับ: 34,
    name: "วิชัยเวช อินเตอร์เนชั่นแนล อ้อมน้อย",
    address: "74/5 หมู่ 4 ถ.เพชรเกษม ต.อ้อมน้อย",
    district: "กระทุ่มแบน",
    province: "สมุทรสาคร",
    postalcode: 74130,
    tel: "02-4310070",
    region: "ภำคกลำง (CENTRAL)",
  },
  {
    ลำดับ: 35,
    name: "บ้านแพ้ว",
    address: "198 หมู่ 1 ต.บ้านแพ้ว",
    district: "บ้านแพ้ว",
    province: "สมุทรสาคร",
    postalcode: 74120,
    tel: "034-419501,034-419526",
    region: "ภำคกลำง (CENTRAL)",
  },
  {
    ลำดับ: 36,
    name: "มหาชัยแม่กลอง โรงพยาบาลทั่วไปขนาดกลาง (แม่กลอง)",
    address: "158/1 ถ.ราษฎร์ประสิทธิ์ ต.แม่กลอง",
    district: "เมือง",
    province: "สมุทรสงคราม",
    postalcode: 75000,
    tel: "034-715001-5",
    region: "ภำคกลำง (CENTRAL)",
  },
  {
    ลำดับ: 37,
    name: "สมเด็จพระพุทธเลิศหล้า",
    address: "708 ถนนประสิทธิ์พัฒนา ตำบลแม่กลอง",
    district: "เมือง",
    province: "สมุทรสงคราม",
    postalcode: 75000,
    tel: "034-723044-9",
    region: "ภำคกลำง (CENTRAL)",
  },
  {
    ลำดับ: 38,
    name: "เกษมราษฏร์ สระบุรี",
    address: "2/22 ถ.มิตรภาพ ต.ปากเพรียว",
    district: "เมือง",
    province: "สระบุรี",
    postalcode: 18000,
    tel: "036-315555-93",
    region: "ภำคกลำง (CENTRAL)",
  },
  {
    ลำดับ: 39,
    name: "มิตรภาพเมโมเรียล สระบุรี",
    address: "9/1 ถนนมิตรภาพ ต.บางเพรียว",
    district: "เมือง",
    province: "สระบุรี",
    postalcode: 18000,
    tel: "036-401100-11 , 036-212131-4",
    region: "ภำคกลำง (CENTRAL)",
  },
  {
    ลำดับ: 40,
    name: "สิงห์บุรีเวชชการ",
    address: "80/1 หมู่6 ถ.สิงห์บุรี-อ่างทอง ต.ต้นโพธิ์",
    district: "เมือง",
    province: "สิงห์บุรี",
    postalcode: 16000,
    tel: "036-520517",
    region: "ภำคกลำง (CENTRAL)",
  },
  {
    ลำดับ: 41,
    name: "ศุภมิตร สุพรรณบุรี",
    address: "76 ถ.เณรแก้ว ต.ท่าพี่เลี้ยง",
    district: "เมือง",
    province: "สุพรรณบุรี",
    postalcode: 72000,
    tel: "035-500283-8",
    region: "ภำคกลำง (CENTRAL)",
  },
  {
    ลำดับ: 42,
    name: "ธนบุรี อู่ทอง",
    address: "2000/22 ม.6 ถ.มาลัยแมน ต.อู่ทอง",
    district: "อู่ทอง",
    province: "สุพรรณบุรี",
    postalcode: 72160,
    tel: "035-551673-7",
    region: "ภำคกลำง (CENTRAL)",
  },
  {
    ลำดับ: 43,
    name: "วิภาวดี-ปิยราษฎร์",
    address: "1618/1 หมู่6 ต.อู่ทอง",
    district: "อู่ทอง",
    province: "สุพรรณบุรี",
    postalcode: 72160,
    tel: "035-552724",
    region: "ภำคกลำง (CENTRAL)",
  },
  {
    ลำดับ: 44,
    name: "อ่างทองเวชชการ 2",
    address: "29/9 หมู่ 2 ต.ศาลาแดง",
    district: "เมือง",
    province: "อ่างทอง",
    postalcode: 14000,
    tel: "035-612361-4",
    region: "ภำคกลำง (CENTRAL)",
  },
  {
    ลำดับ: 1,
    name: "กระบี่",
    address: "325 ถนนอุตรกิจ ต.ปากน้ำ",
    district: "เมือง",
    province: "กระบี่",
    postalcode: 81000,
    tel: "075-611212",
    region: "ภำคใต้ (SOUTH )",
  },
  {
    ลำดับ: 2,
    name: "รวมแพทย์ กระบี่",
    address: "529 ถนนอุตรกิจ ต.กระบี่ใหม่",
    district: "เมือง",
    province: "กระบี่",
    postalcode: 81000,
    tel: "075-632204",
    region: "ภำคใต้ (SOUTH )",
  },
  {
    ลำดับ: 3,
    name: "กระบี่นครินทร์ อินเตอร์เนชั่นแนล",
    address: "1 ถ.พิศาลภพ ต.ปากน้ำ",
    district: "เมือง",
    province: "กระบี่",
    postalcode: 81000,
    tel: "075-626555",
    region: "ภำคใต้ (SOUTH )",
  },
  {
    ลำดับ: 4,
    name: "ธนบุรี ชุมพร",
    address: "121 ม.3 ต.วังไผ่",
    district: "เมือง",
    province: "ชุมพร",
    postalcode: 86000,
    tel: "077-658617-28",
    region: "ภำคใต้ (SOUTH )",
  },
  {
    ลำดับ: 5,
    name: "วิรัชศิลป์",
    address: "18/22 ถ.ปรมินทรมรรคา ต.ท่าตะเภา",
    district: "เมือง",
    province: "ชุมพร",
    postalcode: 86000,
    tel: "077-503238-40",
    region: "ภำคใต้ (SOUTH )",
  },
  {
    ลำดับ: 6,
    name: "พะโต๊ะ (ยุตติสัญญา)",
    address: "138 ม.8 ต.พะโต๊ะ",
    district: "พะโต๊ะ",
    province: "ชุมพร",
    postalcode: 86180,
    tel: "077-539044-6",
    region: "ภำคใต้ (SOUTH )",
  },
  {
    ลำดับ: 7,
    name: "ตรังรวมแพทย์",
    address: "61/39 ถ.โคกขัน ต.ทับเที่ยง",
    district: "เมือง",
    province: "ตรัง",
    postalcode: 92000,
    tel: "075-218988",
    region: "ภำคใต้ (SOUTH )",
  },
  {
    ลำดับ: 8,
    name: "วัฒนแพทย์ตรัง",
    address: "247/2 ถ.พัทลุง ต.ทับเที่ยง",
    district: "เมือง",
    province: "ตรัง",
    postalcode: 92000,
    tel: "075-205555",
    region: "ภำคใต้ (SOUTH )",
  },
  {
    ลำดับ: 9,
    name: "นครคริสเตียน",
    address: "1110/2 ถ.ศรีปราชญ์ ต.คลัง",
    district: "เมือง",
    province: "นครศรีธรรมราช",
    postalcode: 80000,
    tel: "075-317109-10",
    region: "ภำคใต้ (SOUTH )",
  },
  {
    ลำดับ: 10,
    name: "นครพัฒน์",
    address: "2/99 ถ.พัฒนาการคูขวาง ต. ในเมือง",
    district: "เมือง",
    province: "นครศรีธรรมราช",
    postalcode: 80000,
    tel: "075-305999",
    region: "ภำคใต้ (SOUTH )",
  },
  {
    ลำดับ: 11,
    name: "นครินทร์",
    address: "61 อ้อมค่ายวชิราวุธ ต.ท่าวัง",
    district: "เมือง",
    province: "นครศรีธรรมราช",
    postalcode: 80000,
    tel: "075-312800-15",
    region: "ภำคใต้ (SOUTH )",
  },
  {
    ลำดับ: 12,
    name: "ซาน เปาโล หัวหิน",
    address: "222 ถ.เพชรเกษม",
    district: "หัวหิน",
    province: "ประจวบคีรีขันธ์",
    postalcode: 77110,
    tel: "032-532576-85",
    region: "ภำคใต้ (SOUTH )",
  },
  {
    ลำดับ: 13,
    name: "กรุงเทพ หัวหิน",
    address: "888 ถนนเพชรเกษม ตำบลหัวหิน",
    district: "หัวหิน",
    province: "ประจวบคีรีขันธ์",
    postalcode: 77110,
    tel: "032-616800",
    region: "ภำคใต้ (SOUTH )",
  },
  {
    ลำดับ: 14,
    name: "พังงา",
    address: "436 ถ.เพชรเกษม ต.ท้ายช้าง",
    district: "เมือง",
    province: "พังงา",
    postalcode: 82000,
    tel: "076-411618-9",
    region: "ภำคใต้ (SOUTH )",
  },
  {
    ลำดับ: 15,
    name: "ตะกั่วป่า",
    address: "39/3 หมู่ 1 ถ. เพชรเกษม ต. บางนายสี",
    district: "ตะกั่วป่า",
    province: "พังงา",
    postalcode: 82110,
    tel: "076-584250 , 076-421770,076-421138",
    region: "ภำคใต้ (SOUTH )",
  },
  {
    ลำดับ: 16,
    name: "พัทลุง",
    address: "421 ถนนราเมศวร์ ตำบลคูหาสวรรค์",
    district: "เมือง",
    province: "พัทลุง",
    postalcode: 93000,
    tel: "074 - 609500",
    region: "ภำคใต้ (SOUTH )",
  },
  {
    ลำดับ: 17,
    name: "กรุงเทพภูเก็ต",
    address: "2/1 ถ.หงษ์หยกอุทิศ ต.ตลาดใหม่",
    district: "เมือง",
    province: "ภูเก็ต",
    postalcode: 83000,
    tel: "076-254421-4",
    region: "ภำคใต้ (SOUTH )",
  },
  {
    ลำดับ: 18,
    name: "มิชชั่นภูเก็ต",
    address: "4/1 ม.3 ถ.เทพกษัตริย์ ต.รัชฎา",
    district: "เมือง",
    province: "ภูเก็ต",
    postalcode: 83000,
    tel: "076-237220-6",
    region: "ภำคใต้ (SOUTH )",
  },
  {
    ลำดับ: 19,
    name: "วชิระภูเก็ต",
    address: "353 ถนนเยาวราช ตำบลตลาดใหญ่",
    district: "เมือง",
    province: "ภูเก็ต",
    postalcode: 83001,
    tel: "076-361236",
    region: "ภำคใต้ (SOUTH )",
  },
  {
    ลำดับ: 20,
    name: "สิริโรจน์",
    address: "44 ถ.เฉลิมพระเกียรติ ร.9 ต.วิชิต",
    district: "เมือง",
    province: "ภูเก็ต",
    postalcode: 83000,
    tel: "076-249400",
    region: "ภำคใต้ (SOUTH )",
  },
  {
    ลำดับ: 21,
    name: "องค์การบริหารส่วนจังหวัดภูเก็ต",
    address: "18,20 ถนนอนุภาษภูเก็ตการ ตำบลตลาดใหญ่",
    district: "เมือง",
    province: "ภูเก็ต",
    postalcode: 83000,
    tel: "076-358888",
    region: "ภำคใต้ (SOUTH )",
  },
  {
    ลำดับ: 22,
    name: "ดีบุก",
    address: "89/8-9 หมู่ 2ต.วิชิต",
    district: "เมือง",
    province: "ภูเก็ต",
    postalcode: 83000,
    tel: "076-254555",
    region: "ภำคใต้ (SOUTH )",
  },
  {
    ลำดับ: 23,
    name: "สิโรรส",
    address: "247-249 ถ.สิโรรส ต.สะเตง",
    district: "เมือง",
    province: "ยะลา",
    postalcode: 95000,
    tel: "073-221114-5",
    region: "ภำคใต้ (SOUTH )",
  },
  {
    ลำดับ: 24,
    name: "กรุงเทพ หาดใหญ่",
    address: "75 ซอย 15 ถ.เพชรเกษม",
    district: "หาดใหญ่",
    province: "สงขลา",
    postalcode: 90110,
    tel: "074-365780-9",
    region: "ภำคใต้ (SOUTH )",
  },
  {
    ลำดับ: 25,
    name: "ราษฎร์ยินดี",
    address: "119 ถ.ราษฎร์ยินดี",
    district: "หาดใหญ่",
    province: "สงขลา",
    postalcode: 90110,
    tel: "074-200200",
    region: "ภำคใต้ (SOUTH )",
  },
  {
    ลำดับ: 26,
    name: "ศิครินทร์ หาดใหญ่",
    address: "169 ถ.นิพัทธ์สงเคราะห์ 1",
    district: "หาดใหญ่",
    province: "สงขลา",
    postalcode: 90110,
    tel: "074-366966",
    region: "ภำคใต้ (SOUTH )",
  },
  {
    ลำดับ: 27,
    name: "ไทยอินเตอร์เนชั่นแนล",
    address: "25/25 ม.6 ต.บ่อผุด",
    district: "เกาะสมุย",
    province: "สุราษฎร์ธานี",
    postalcode: 84320,
    tel: "077-245721-6",
    region: "ภำคใต้ (SOUTH )",
  },
  {
    ลำดับ: 28,
    name: "กรุงเทพสมุย",
    address: "57 หมู่ 3 ถนนทวีราษฎร์ภักดี ต.บ่อผุด",
    district: "เกาะสมุย",
    province: "สุราษฎร์ธานี",
    postalcode: 84320,
    tel: "077-429500",
    region: "ภำคใต้ (SOUTH )",
  },
  {
    ลำดับ: 29,
    name: "บ้านดอนอินเตอร์",
    address: "123/1 ม. 1 ต.บ่อผุด",
    district: "เกาะสมุย",
    province: "สุราษฎร์ธานี",
    postalcode: 84320,
    tel: "077-245236-8",
    region: "ภำคใต้ (SOUTH )",
  },
  {
    ลำดับ: 30,
    name: "สมุยอินเตอร์เนชั่นแนล",
    address: "90/2 หมู่ 2 ต.บ่อผุด",
    district: "เกาะสมุย",
    province: "สุราษฎร์ธานี",
    postalcode: 84320,
    tel: "077-230781-2",
    region: "ภำคใต้ (SOUTH )",
  },
  {
    ลำดับ: 31,
    name: "ทักษิณ",
    address: "309/2 ถ.ตลาดใหม่ ต.ตลาด",
    district: "เมือง",
    province: "สุราษฎร์ธานี",
    postalcode: 84000,
    tel: "077-285701-5",
    region: "ภำคใต้ (SOUTH )",
  },
  {
    ลำดับ: 32,
    name: "ศรีวิชัย สุราษฎร์ธานี",
    address: "67/47-50 หมู่ 2 ถ. ศรีวิชัย ต.มะขามเตี้ย",
    district: "เมือง",
    province: "สุราษฎร์ธานี",
    postalcode: 84000,
    tel: "077-282520-21",
    region: "ภำคใต้ (SOUTH )",
  },
  {
    ลำดับ: 1,
    name: "เอกชนเมืองกำแพง",
    address: "68 ถนนเลี่ยงเมือง ตำบลในเมือง",
    district: "เมือง",
    province: "กำแพงเพชร",
    postalcode: 62000,
    tel: "055-716701-5",
    region: "ภำคเหนือ (NORTH)",
  },
  {
    ลำดับ: 2,
    name: "เชียงใหม่ ราม",
    address: "8 ถ.บุญเรืองฤทธิ์",
    district: "เมือง",
    province: "เชียงใหม่",
    postalcode: 50000,
    tel: "053-920300",
    region: "ภำคเหนือ (NORTH)",
  },
  {
    ลำดับ: 3,
    name: "เชียงใหม่ใกล้หมอ",
    address: "157/16-19 ถ.เชียงใหม่-ฮอต",
    district: "เมือง",
    province: "เชียงใหม่",
    postalcode: 50100,
    tel: "053-200002",
    region: "ภำคเหนือ (NORTH)",
  },
  {
    ลำดับ: 4,
    name: "เซ็นทรัลเชียงใหม่เมโมเรียล",
    address: "186 ถ.ช้างคลาน ต.ช้างคลาน",
    district: "เมือง",
    province: "เชียงใหม่",
    postalcode: 50000,
    tel: "053-819333-40",
    region: "ภำคเหนือ (NORTH)",
  },
  {
    ลำดับ: 5,
    name: "เทพปัญญา",
    address: "99 หมู่5 ถ.เชียงใหม่-ลำปาง",
    district: "เมือง",
    province: "เชียงใหม่",
    postalcode: 50000,
    tel: "053-852590",
    region: "ภำคเหนือ (NORTH)",
  },
  {
    ลำดับ: 6,
    name: "แมคคอร์มิค",
    address: "133 ถนนแก้วนวรัฐ ตำบลวัดเกต",
    district: "เมือง",
    province: "เชียงใหม่",
    postalcode: 50000,
    tel: "053-921777",
    region: "ภำคเหนือ (NORTH)",
  },
  {
    ลำดับ: 7,
    name: "ราชเวช เชียงใหม่",
    address: "316/1 ถ.เชียงใหม่-ลำพูน ต.วัดเกตุ",
    district: "เมือง",
    province: "เชียงใหม่",
    postalcode: 50000,
    tel: "053-801999",
    region: "ภำคเหนือ (NORTH)",
  },
  {
    ลำดับ: 8,
    name: "ลานนา",
    address: "1 ถนนสุขเกษม แขวงนครพิงค์ ต.ป่าตัน",
    district: "เมือง",
    province: "เชียงใหม่",
    postalcode: 50300,
    tel: "053-999-777",
    region: "ภำคเหนือ (NORTH)",
  },
  {
    ลำดับ: 9,
    name: "ศูนย์ศรีพัฒน์ คณะแพทยศาสตร์ มหาวิทยาลัยเชียงใหม่",
    address: "110/392 อาคารศรีพัฒน์ ถ.อินทวโรรส ต.ศรีภู",
    district: "เมือง",
    province: "เชียงใหม่",
    postalcode: 50200,
    tel: "053-946505",
    region: "ภำคเหนือ (NORTH)",
  },
  {
    ลำดับ: 10,
    name: "เชียงใหม่ ฮอสพิทอล (สยามราษฏร์ เชียงใหม่)",
    address: "84/3 ถ.เชียงใหม่-ลำปาง ต.ช้างเผือก",
    district: "เมือง",
    province: "เชียงใหม่",
    postalcode: 50300,
    tel: "053-215020-2",
    region: "ภำคเหนือ (NORTH)",
  },
  {
    ลำดับ: 11,
    name: "กรุงเทพ เชียงใหม่",
    address: "88/8 หมู่ 6 ถ.ซุปเปอ์ไฮเวย์ ต.หนองป่าครั่ง",
    district: "เมือง",
    province: "เชียงใหม่",
    postalcode: 50000,
    tel: "052-089888",
    region: "ภำคเหนือ (NORTH)",
  },
  {
    ลำดับ: 12,
    name: "เกษมราษฎร์ ศรีบุรินทร์",
    address: "111/5 ถ.เอเชีย ต.สันทราย",
    district: "เมือง",
    province: "เชียงราย",
    postalcode: 57000,
    tel: "053-910999,053-717499",
    region: "ภำคเหนือ (NORTH)",
  },
  {
    ลำดับ: 13,
    name: "โอเวอร์บรุ๊ค",
    address: "17 ถ.สิงหไคล ต.เวียง",
    district: "เมือง",
    province: "เชียงราย",
    postalcode: 57000,
    tel: "053-711366",
    region: "ภำคเหนือ (NORTH)",
  },
  {
    ลำดับ: 14,
    name: "เชียงรายอินเตอร์",
    address: "123 หมู่ 26 ถนนพหลโยธิน ตำบลรอบเวียง",
    district: "เมือง",
    province: "เชียงราย",
    postalcode: 57000,
    tel: "053-719719",
    region: "ภำคเหนือ (NORTH)",
  },
  {
    ลำดับ: 15,
    name: "เพชรรัตน์ เพชรบูรณ์",
    address: "2/1 ถ.สามัคคีชัย ต.ในเมือง",
    district: "เมือง",
    province: "เพชรบูรณ์",
    postalcode: 67000,
    tel: "056-720680-4",
    region: "ภำคเหนือ (NORTH)",
  },
  {
    ลำดับ: 16,
    name: "เมืองเพชร (เพชรบูรณ์)",
    address: "9 ถ.เพชรรัตน์ ต.ในเมือง",
    district: "เมือง",
    province: "เพชรบูรณ์",
    postalcode: 67000,
    tel: "056-748030-3",
    region: "ภำคเหนือ (NORTH)",
  },
  {
    ลำดับ: 17,
    name: "โรงพยาบาลทั่วไปขนาดเล็กนครหล่ม",
    address: "163/75 ถ.คชเสนีย์ ต. หล่มสัก",
    district: "หล่มสัก",
    province: "เพชรบูรณ์",
    postalcode: 67110,
    tel: "056-702015-7",
    region: "ภำคเหนือ (NORTH)",
  },
  {
    ลำดับ: 18,
    name: "พิษณุเวช",
    address: "211 ถ.ขุนพิเรนทรเทพ ต.ในเมือง",
    district: "เมือง",
    province: "พิษณุโลก",
    postalcode: 65000,
    tel: "055-909000",
    region: "ภำคเหนือ (NORTH)",
  },
  {
    ลำดับ: 19,
    name: "รวมแพทย์พิษณุโลก",
    address: "224/30 ถ.บรมไตรโลกนาถ ต.ในเมือง",
    district: "เมือง",
    province: "พิษณุโลก",
    postalcode: 65000,
    tel: "055-219307",
    region: "ภำคเหนือ (NORTH)",
  },
  {
    ลำดับ: 20,
    name: "กรุงเทพ พิษณุโลก",
    address: "138 ถนนพระองค์ดำ ตำบลในเมือง",
    district: "เมือง",
    province: "พิษณุโลก",
    postalcode: 65000,
    tel: "055-212222 , 055-210819-27",
    region: "ภำคเหนือ (NORTH)",
  },
  {
    ลำดับ: 21,
    name: "พิษณุโลก ฮอสพิทอล (อินเตอร์เวชการ พิษณุโลก )",
    address: "262/55 ถ.บรมไตรโลกนาถ ต.ในเมือง",
    district: "เมือง",
    province: "พิษณุโลก",
    postalcode: 65000,
    tel: "055-218777",
    region: "ภำคเหนือ (NORTH)",
  },
  {
    ลำดับ: 22,
    name: "แพร่คริสเตียน",
    address: "7 ถ.ยัตรกิจโกศล ต.ในเวียง",
    district: "เมือง",
    province: "แพร่",
    postalcode: 54000,
    tel: "054-511017",
    region: "ภำคเหนือ (NORTH)",
  },
  {
    ลำดับ: 23,
    name: "แพร่-ราม",
    address: "3 ตรอกยนตรกิจโกศล ถ.ยันตรกิจโกศล ต.ในเวียง",
    district: "เมือง",
    province: "แพร่",
    postalcode: 54000,
    tel: "054-522911-13",
    region: "ภำคเหนือ (NORTH)",
  },
  {
    ลำดับ: 24,
    name: "พะเยา ราม",
    address: "660 หมู่3 ต.ท่าวังทอง",
    district: "เมือง",
    province: "พะเยา",
    postalcode: 56000,
    tel: "054-411111-40",
    region: "ภำคเหนือ (NORTH)",
  },
  {
    ลำดับ: 25,
    name: "ชัยอรุณเวชการ",
    address: "31/12 ถนนสระหลวง ตำบลในเมือง",
    district: "เมือง",
    province: "พิจิตร",
    postalcode: 66000,
    tel: "056-651407",
    region: "ภำคเหนือ (NORTH)",
  },
  {
    ลำดับ: 26,
    name: "สหเวช",
    address: "2/158 ถ.ศรีมาลา ต.ในเมือง",
    district: "เมือง",
    province: "พิจิตร",
    postalcode: 66000,
    tel: "056-612791-3",
    region: "ภำคเหนือ (NORTH)",
  },
  {
    ลำดับ: 27,
    name: "แม่สอด-ราม (พะวอ)",
    address: "3/24 ถ.ราชอุทิศ ต.แม่สอด",
    district: "แม่สอด",
    province: "ตาก",
    postalcode: 63110,
    tel: "055-533912-5",
    region: "ภำคเหนือ (NORTH)",
  },
  {
    ลำดับ: 28,
    name: "นครแม่สอด อินเตอร์เนชั่นแนล",
    address: "222 หมู่9 ต.แม่ปะ",
    district: "แม่สอด",
    province: "ตาก",
    postalcode: 63110,
    tel: "055-518200-22",
    region: "ภำคเหนือ (NORTH)",
  },
  {
    ลำดับ: 29,
    name: "ท่าวังผา",
    address: "84 หมู่ 1 ต.ท่าวังผา",
    district: "ท่าวังผา",
    province: "น่าน",
    postalcode: 55140,
    tel: "054-755380",
    region: "ภำคเหนือ (NORTH)",
  },
  {
    ลำดับ: 30,
    name: "เขลางค์นคร ราม",
    address: "79/12 ถ.พหลโยธิน ต.สวนดอก",
    district: "เมือง",
    province: "ลำปาง",
    postalcode: 52100,
    tel: "054-019619",
    region: "ภำคเหนือ (NORTH)",
  },
  {
    ลำดับ: 31,
    name: "หริภุญชัยเมโมเรียล",
    address: "109 - 111 หมู่4 ต.บ้านกลาง",
    district: "เมือง",
    province: "ลำพูน",
    postalcode: 51000,
    tel: "053-581600-6",
    region: "ภำคเหนือ (NORTH)",
  },
  {
    ลำดับ: 32,
    name: "พัฒนเวช สุโขทัย",
    address: "89/9 ถ.สิงหวัฒน์ ต.ธานี",
    district: "เมือง",
    province: "สุโขทัย",
    postalcode: 64000,
    tel: "055-621502-7",
    region: "ภำคเหนือ (NORTH)",
  },
  {
    ลำดับ: 33,
    name: "รวมแพทย์สุโขทัย",
    address: "151 ถ.จรดวิถีสอง ต.บ้านกล้วย",
    district: "เมือง",
    province: "สุโขทัย",
    postalcode: 64000,
    tel: "055-612211-12",
    region: "ภำคเหนือ (NORTH)",
  },
  {
    ลำดับ: 1,
    name: "กรุงเทพจันทบุรี",
    address: "25/14 ถ.ท่าหลวง ต.วัดใหม่",
    district: "เมือง",
    province: "จันทบุรี",
    postalcode: 22000,
    tel: "039-319888",
    region: "ภำคตะวันออก (EAST)",
  },
  {
    ลำดับ: 2,
    name: "สิริเวช",
    address: "151 หมู่ 7 ถ.ตรีรัตน์ ต.จันทนิมิต",
    district: "เมือง",
    province: "จันทบุรี",
    postalcode: 22000,
    tel: "039-605666",
    region: "ภำคตะวันออก (EAST)",
  },
  {
    ลำดับ: 3,
    name: "เกษมราษฎร์ ฉะเชิงเทรา (โสธราเวช)",
    address: "29 ถนนสุวินทวงศ์ ต.หน้าเมือง",
    district: "เมือง",
    province: "ฉะเชิงเทรา",
    postalcode: 24000,
    tel: "038-812702-19",
    region: "ภำคตะวันออก (EAST)",
  },
  {
    ลำดับ: 4,
    name: "จุฬารัตน์11",
    address: "185/1 ม.1 ถ.บางนา-ตราด กม.42 ต.บางวัว",
    district: "บางปะกง",
    province: "ฉะเชิงเทรา",
    postalcode: 24180,
    tel: "038-538511-3",
    region: "ภำคตะวันออก (EAST)",
  },
  {
    ลำดับ: 5,
    name: "เอกชล",
    address: "68/3 ถนนพระยาสัจจา ต.บ้านสวน",
    district: "เมือง",
    province: "ชลบุรี",
    postalcode: 20000,
    tel: "038-273840-7",
    region: "ภำคตะวันออก (EAST)",
  },
  {
    ลำดับ: 6,
    name: "เอกชล 2",
    address: "31/2 หมู่ 3 ถ.อ่างศิลา ต. เสม็ด",
    district: "เมือง",
    province: "ชลบุรี",
    postalcode: 20000,
    tel: "038-939888",
    region: "ภำคตะวันออก (EAST)",
  },
  {
    ลำดับ: 7,
    name: "จุฬารัตน์ ชลเวช (ชลเวช)",
    address: "104/15 ซ.หน้าวัดต้นสน ถ.อัคนิวาต ต.บางปลาสร้อย",
    district: "เมือง",
    province: "ชลบุรี",
    postalcode: 20000,
    tel: "038-284534-5",
    region: "ภำคตะวันออก (EAST)",
  },
  {
    ลำดับ: 8,
    name: "ชลบุรี",
    address: "69 หมู่ 2 ถ.สุขุมวิท ต. บ้านสวน",
    district: "เมือง",
    province: "ชลบุรี",
    postalcode: 20000,
    tel: "038-931075-6",
    region: "ภำคตะวันออก (EAST)",
  },
  {
    ลำดับ: 9,
    name: "สมิติเวช ชลบุรี",
    address: "888/88 หมู่ 3 ถนนสุขุมวิท ตำบลบ้านสวน",
    district: "เมือง",
    province: "ชลบุรี",
    postalcode: 20000,
    tel: "033-038888",
    region: "ภำคตะวันออก (EAST)",
  },
  {
    ลำดับ: 10,
    name: "ปิยะเวชช์ บ่อวิน",
    address: "28/8 หมู่ 8 ตำบลบ่อวิน",
    district: "ศรีราชา",
    province: "ชลบุรี",
    postalcode: 20230,
    tel: "038-345333,038-345111",
    region: "ภำคตะวันออก (EAST)",
  },
  {
    ลำดับ: 11,
    name: "กรุงเทพ พัทยา",
    address: "301 หมู่ 6 ถ.สุขุมวิท กม.143 ต.นาเกลือ",
    district: "บางละมุง",
    province: "ชลบุรี",
    postalcode: 20150,
    tel: "038-909088",
    region: "ภำคตะวันออก (EAST)",
  },
  {
    ลำดับ: 12,
    name: "พัทยาเมโมเรียล",
    address: "328/1 หมู่ 9 ถนนพัทยากลาง ตำบลหนองปรือ",
    district: "บางละมุง",
    province: "ชลบุรี",
    postalcode: 20000,
    tel: "038-488777",
    region: "ภำคตะวันออก (EAST)",
  },
  {
    ลำดับ: 13,
    name: "วิภาราม แหลมฉบัง",
    address: "107 หมู่ 10 ถนนสุขุมวิท ตำบลทุ่งสุขลา",
    district: "ศรีราชา",
    province: "ชลบุรี",
    postalcode: 20230,
    tel: "038-491888",
    region: "ภำคตะวันออก (EAST)",
  },
  {
    ลำดับ: 14,
    name: "พญาไท ศรีราชา",
    address: "90 ศรีราชานคร ถ.สุขุมวิท",
    district: "ศรีราชา",
    province: "ชลบุรี",
    postalcode: 20110,
    tel: "038-317333",
    region: "ภำคตะวันออก (EAST)",
  },
  {
    ลำดับ: 15,
    name: "สมเด็จพระบรมราชเทวี ณ ศรีราชา สภากาชาดไทย",
    address: "290 ถ.เจิมจอมพล ต.ศรีราชา",
    district: "ศรีราชา",
    province: "ชลบุรี",
    postalcode: 20110,
    tel: "038-322157-9",
    region: "ภำคตะวันออก (EAST)",
  },
  {
    ลำดับ: 16,
    name: "สมิติเวช ศรีราชา",
    address: "8 ซ.แหลมเกตุ ถ.เจิมจอมพล ต.ศรีราชา",
    district: "ศรีราชา",
    province: "ชลบุรี",
    postalcode: 20110,
    tel: "038-320300,038-324100",
    region: "ภำคตะวันออก (EAST)",
  },
  {
    ลำดับ: 17,
    name: "กรุงเทพตราด",
    address: "376 ถ.สุขุมวิท ต.วังกระแจะ",
    district: "เมือง",
    province: "ตราด",
    postalcode: 23000,
    tel: "039-532735-7",
    region: "ภำคตะวันออก (EAST)",
  },
  {
    ลำดับ: 18,
    name: "ตราด",
    address: "108 ถ.สุขุมวิท ต. วังกระแจะ",
    district: "เมือง",
    province: "ตราด",
    postalcode: 23000,
    tel: "039-531784-86",
    region: "ภำคตะวันออก (EAST)",
  },
  {
    ลำดับ: 19,
    name: "กรุงเทพระยอง",
    address: "8 หมู่ 2 ถ.แสงจันทร์เนรมิต ต.เนินพระ",
    district: "เมือง",
    province: "ระยอง",
    postalcode: 21000,
    tel: "038-921999",
    region: "ภำคตะวันออก (EAST)",
  },
  {
    ลำดับ: 20,
    name: "มงกุฎระยอง",
    address: "149/1 ถ.มาบยา ต.มาบตาพุด",
    district: "เมือง",
    province: "ระยอง",
    postalcode: 21150,
    tel: "038-691800-9",
    region: "ภำคตะวันออก (EAST)",
  },
  {
    ลำดับ: 21,
    name: "รวมแพทย์ระยอง",
    address: "065/28 ถ.จันทอุดม ต.ท่าประดู่",
    district: "เมือง",
    province: "ระยอง",
    postalcode: 21000,
    tel: "038-860890-3",
    region: "ภำคตะวันออก (EAST)",
  },
  {
    ลำดับ: 22,
    name: "ระยอง",
    address: "138 ถ.สุขุมวิท ต.ท่าประดู่",
    district: "เมือง",
    province: "ระยอง",
    postalcode: 21000,
    tel: "038-611104",
    region: "ภำคตะวันออก (EAST)",
  },
  {
    ลำดับ: 23,
    name: "ศรีระยอง",
    address: "333/3 หมู่ 4 ตำบลเชิงเนิน",
    district: "เมือง",
    province: "ระยอง",
    postalcode: 21000,
    tel: "038-995800-99",
    region: "ภำคตะวันออก (EAST)",
  },
  {
    ลำดับ: 24,
    name: "วิภาราม อมตะ",
    address: "700/888 หมู่1 ต.คลองตำหรุ",
    district: "เมือง",
    province: "ชลบุรี",
    postalcode: 20000,
    tel: "038-316999",
    region: "ภำคตะวันออก (EAST)",
  },
  {
    ลำดับ: 1,
    name: "ขอนแก่น",
    address: "54 ,56 ถ. ศรีจันทร์ ต. ในเมือง",
    district: "เมือง",
    province: "ขอนแก่น",
    postalcode: 40000,
    tel: "043-336428",
    region: "ภำคตะวันออกเฉียงเหนือ ( NORTH - EAST)",
  },
  {
    ลำดับ: 2,
    name: "ขอนแก่น ราม",
    address: "193 ถ.ศรีจันทร์",
    district: "เมือง",
    province: "ขอนแก่น",
    postalcode: 40000,
    tel: "043-333800",
    region: "ภำคตะวันออกเฉียงเหนือ ( NORTH - EAST)",
  },
  {
    ลำดับ: 3,
    name: "กรุงเทพ ขอนแก่น",
    address: "888 ม.16 ถ.มะลิวัลย์ ต.ในเมือง",
    district: "เมือง",
    province: "ขอนแก่น",
    postalcode: 40001,
    tel: "043 -042721",
    region: "ภำคตะวันออกเฉียงเหนือ ( NORTH - EAST)",
  },
  {
    ลำดับ: 4,
    name: "ราชพฤกษ์",
    address: "150/19 ถ.มิตรภาพ",
    district: "เมือง",
    province: "ขอนแก่น",
    postalcode: 40000,
    tel: "043-333-555-62",
    region: "ภำคตะวันออกเฉียงเหนือ ( NORTH - EAST)",
  },
  {
    ลำดับ: 5,
    name: "ชัยภูมิ ราม",
    address: "290/42 หมู่ 6 บ้านหนองสังข์ ต.ในเมือง",
    district: "เมือง",
    province: "ชัยภูมิ",
    postalcode: 36000,
    tel: "044-836888",
    region: "ภำคตะวันออกเฉียงเหนือ ( NORTH - EAST)",
  },
  {
    ลำดับ: 6,
    name: "ชัยภูมิรวมแพทย์",
    address: "619 ถ.นิเวศรัตน์ ต.ในเมือง",
    district: "เมือง",
    province: "ชัยภูมิ",
    postalcode: 36000,
    tel: "044-813222",
    region: "ภำคตะวันออกเฉียงเหนือ ( NORTH - EAST)",
  },
  {
    ลำดับ: 7,
    name: "เซนต์เมรี่",
    address: "307 ถ.มิตรภาพ-หนองคาย ต.ในเมือง",
    district: "เมือง",
    province: "นครราชสีมา",
    postalcode: 30000,
    tel: "044-261261",
    region: "ภำคตะวันออกเฉียงเหนือ ( NORTH - EAST)",
  },
  {
    ลำดับ: 8,
    name: "กรุงเทพ ราชสีมา",
    address: "1308/9 ถ.มิตรภาพ ต.ในเมือง",
    district: "เมือง",
    province: "นครราชสีมา",
    postalcode: 30000,
    tel: "044-429999",
    region: "ภำคตะวันออกเฉียงเหนือ ( NORTH - EAST)",
  },
  {
    ลำดับ: 9,
    name: "ป.แพทย์",
    address: "45-53 ถ.ไชยณรงค์ ต.ในเมือง",
    district: "เมือง",
    province: "นครราชสีมา",
    postalcode: 30000,
    tel: "044-230530-3 , 044-230530-2 ตึก2",
    region: "ภำคตะวันออกเฉียงเหนือ ( NORTH - EAST)",
  },
  {
    ลำดับ: 10,
    name: "มหาวิทยาลัยเทคโนโลยีสุรนารี",
    address: "111 ถนนมหาวิทยาลัย ต.สุรนารี",
    district: "เมือง",
    province: "นครราชสีมา",
    postalcode: 30001,
    tel: "044-376-555",
    region: "ภำคตะวันออกเฉียงเหนือ ( NORTH - EAST)",
  },
  {
    ลำดับ: 11,
    name: "บัวใหญ่รวมแพทย์",
    address: "5/1 ถ.เทศบาล5 ต.บัวใหญ่",
    district: "บัวใหญ่",
    province: "นครราชสีมา",
    postalcode: 30120,
    tel: "044-292249-53",
    region: "ภำคตะวันออกเฉียงเหนือ ( NORTH - EAST)",
  },
  {
    ลำดับ: 12,
    name: "กรุงเทพ ปากช่อง",
    address: "5/1 ถนนมิตรภาพ ตำบลหนองสาหร่าย",
    district: "ปากช่อง",
    province: "นครราชสีมา",
    postalcode: 30130,
    tel: "044-316611-5,044-279898,044-279901",
    region: "ภำคตะวันออกเฉียงเหนือ ( NORTH - EAST)",
  },
  {
    ลำดับ: 13,
    name: "เอกชน บุรีรัมย์",
    address: "197 ต.ชุมเห็ด",
    district: "เมือง",
    province: "บุรีรัมย์",
    postalcode: 31000,
    tel: "044-614100-7",
    region: "ภำคตะวันออกเฉียงเหนือ ( NORTH - EAST)",
  },
  {
    ลำดับ: 14,
    name: "มหาสารคามอินเตอร์เนชั่นแนล",
    address: "112 ถ.เทศบาลอาชา",
    district: "เมือง",
    province: "มหาสารคาม",
    postalcode: 44000,
    tel: "043-723669",
    region: "ภำคตะวันออกเฉียงเหนือ ( NORTH - EAST)",
  },
  {
    ลำดับ: 15,
    name: "มุกดาหาร อินเตอร์เนชั่นแนล",
    address: "87 ถ.มุกดาหาร-ดอนตาล ต.ศรีบุญเรือง",
    district: "เมือง",
    province: "มุกดาหาร",
    postalcode: 49000,
    tel: "042-633301-9",
    region: "ภำคตะวันออกเฉียงเหนือ ( NORTH - EAST)",
  },
  {
    ลำดับ: 16,
    name: "นายแพทย์หาญ",
    address: "160-164 ถ.วิทยธำรงค์ ต.ในเมือง",
    district: "เมือง",
    province: "ยโสธร",
    postalcode: 35000,
    tel: "045-711356",
    region: "ภำคตะวันออกเฉียงเหนือ ( NORTH - EAST)",
  },
  {
    ลำดับ: 17,
    name: "รวมแพทย์ ยโสธร (หาญอินเตอร์)",
    address: "29 ม.- ซ.- ถ.มงคลบูรพา ต.ในเมือง",
    district: "เมือง",
    province: "ยโสธร",
    postalcode: 35000,
    tel: "045-712141-2",
    region: "ภำคตะวันออกเฉียงเหนือ ( NORTH - EAST)",
  },
  {
    ลำดับ: 18,
    name: "ทั่วไปขนาดใหญ่จุรีเวช (กรุงเทพ จุรีเวช)",
    address: "368 ถ.เทวภิบาล",
    district: "เมือง",
    province: "ร้อยเอ็ด",
    postalcode: 45000,
    tel: "043-527111",
    region: "ภำคตะวันออกเฉียงเหนือ ( NORTH - EAST)",
  },
  {
    ลำดับ: 19,
    name: "ร้อยเอ็ดธนบุรี",
    address: "166 หมู่ที่ ซอย ถนน ปัทมานนท์ แขวง/ตำบล ในเมือง",
    district: "เมือง",
    province: "ร้อยเอ็ด",
    postalcode: 45000,
    tel: "043-515191",
    region: "ภำคตะวันออกเฉียงเหนือ ( NORTH - EAST)",
  },
  {
    ลำดับ: 20,
    name: "เมืองเลย ราม",
    address: "546 หมู่1 ต.นาอาน",
    district: "เมือง",
    province: "เลย",
    postalcode: 42000,
    tel: "042-833400",
    region: "ภำคตะวันออกเฉียงเหนือ ( NORTH - EAST)",
  },
  {
    ลำดับ: 21,
    name: "ประชารักษ์เวชการ",
    address: "872 ถ.อุบล ต.เมืองใต้",
    district: "เมือง",
    province: "ศรีสะเกษ",
    postalcode: 33000,
    tel: "045-631313-9",
    region: "ภำคตะวันออกเฉียงเหนือ ( NORTH - EAST)",
  },
  {
    ลำดับ: 22,
    name: "รักษ์สกล",
    address: "1446/47 ถ.รอบเมือง ต.ธาตุเชิงชม",
    district: "เมือง",
    province: "สกลนคร",
    postalcode: 47000,
    tel: "042-712800",
    region: "ภำคตะวันออกเฉียงเหนือ ( NORTH - EAST)",
  },
  {
    ลำดับ: 23,
    name: "รวมแพทย์สุรินทร์",
    address: "312/1 ถ.เทศบาล 1 ต.ในเมือง",
    district: "เมือง",
    province: "สุรินทร์",
    postalcode: 32000,
    tel: "044-515700-1",
    region: "ภำคตะวันออกเฉียงเหนือ ( NORTH - EAST)",
  },
  {
    ลำดับ: 24,
    name: "รวมแพทย์หนองคาย",
    address: "710 ซ.พรมดำหริห์ ถ.ประจักษ์ ต.ในเมือง",
    district: "เมือง",
    province: "หนองคาย",
    postalcode: 43000,
    tel: "042-421412-4",
    region: "ภำคตะวันออกเฉียงเหนือ ( NORTH - EAST)",
  },
  {
    ลำดับ: 25,
    name: "หนองคายวัฒนา",
    address: "1159/4 หมู่2 ถ.ประจักษ์ ต.ในเมือง",
    district: "เมือง",
    province: "หนองคาย",
    postalcode: 43000,
    tel: "042-465201-8",
    region: "ภำคตะวันออกเฉียงเหนือ ( NORTH - EAST)",
  },
  {
    ลำดับ: 26,
    name: "วีระพลการแพทย์",
    address: "12 ถ.วิจารณ์รังสรรค์ ต.ลำภู",
    district: "เมือง",
    province: "หนองบัวลำภู",
    postalcode: 39000,
    tel: "042-312344-6",
    region: "ภำคตะวันออกเฉียงเหนือ ( NORTH - EAST)",
  },
  {
    ลำดับ: 27,
    name: "เอกอุดร",
    address: "555/5 ถ. โพศรี ต. หมากแข้ง",
    district: "เมือง",
    province: "อุดรธานี",
    postalcode: 41000,
    tel: "042-342555",
    region: "ภำคตะวันออกเฉียงเหนือ ( NORTH - EAST)",
  },
  {
    ลำดับ: 28,
    name: "นอร์ทอีสเทอร์น วัฒนา",
    address: "70/7-8 ถ.ศุภกิจจรรยา ต.หมากแข้ง",
    district: "เมือง",
    province: "อุดรธานี",
    postalcode: 41000,
    tel: "042-325999",
    region: "ภำคตะวันออกเฉียงเหนือ ( NORTH - EAST)",
  },
  {
    ลำดับ: 29,
    name: "กรุงเทพ อุดร",
    address: "111 ถนนทองใหญ่ ต.หมากแข้ง",
    district: "เมือง",
    province: "อุดรธานี",
    postalcode: 41000,
    tel: "042-343111",
    region: "ภำคตะวันออกเฉียงเหนือ ( NORTH - EAST)",
  },
  {
    ลำดับ: 30,
    name: "ราชเวชอุบลราชธานี",
    address: "999 ถ.ชยางกูร ต.ในเมือง",
    district: "เมือง",
    province: "อุบลราชธานี",
    postalcode: 34000,
    tel: "045-280040-55",
    region: "ภำคตะวันออกเฉียงเหนือ ( NORTH - EAST)",
  },
  {
    ลำดับ: 31,
    name: "อุบลรักษ์ ธนบุรี",
    address: "46/4 ถ.บูรพาใน ต.ในเมือง",
    district: "เมือง",
    province: "อุบลราชธานี",
    postalcode: 34000,
    tel: "045-260300",
    region: "ภำคตะวันออกเฉียงเหนือ ( NORTH - EAST)",
  },
];

Promise.all(
  hotels.map((hotel) => {
    const body = {
      name: hotel.name,
      address: hotel.address,
      district: hotel.district,
      province: hotel.province,
      postalcode: hotel.postalcode,
      tel: hotel.tel,
      region: hotel.region,
    };
    fetch("http://localhost:5555/api/v1/hotels", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "Authorization": `Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZDE5MDRlNjE0ZTQ2YzFkNzI5MjFiYyIsImlhdCI6MTc0MTc4NzIxNywiZXhwIjoxNzQ0Mzc5MjE3fQ.b54WMFTQ4FJEYYvLH4N1bSvn-Pm9DIcScDAg5gDvPIc`
      },
      body: JSON.stringify(body),
    })
      .then((response) => response.json()) // แปลง response เป็น JSON
      .then((data) => console.log("Success:", data))
      .catch((error) => console.error("Error:", error));
  })
)
  .then(() => console.log("All requests completed!"))
  .catch((error) => console.error("Some requests failed:", error));
